### ISSUE TITLE
AutoCCompleted event

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#166] opened 2015-12-20 21:25 UTC
AutoCCompleted event does not seem to be triggering after pressing TAB, RETURN or double-clicking the item to be inserted.

**Comment by jacobslusser** [comment] 2015-12-20 21:53
I noticed that also when I added support. See my commit notes: 0013df2c3d2252bf86b70ef3d932ff8cd8713324.

Perhaps you'll spot something I missed when adding the code. I'm not sure what the issue is...

**Comment by robmburke** [comment] 2015-12-21 05:19
Added a pull request for this.  I actually did find the issue.  The integer range (2000-2029) for SCN_ WM codes in WmReflectNotify was stopping on FOCUSOUT (2029), right before the integer value (2030) for AUTOCCOMPLETED.

**Comment by jacobslusser** [comment] 2015-12-21 22:32
I'm impressed that you found that. Thanks. I've merged the pull request.

**Comment by robmburke** [comment] 2015-12-21 23:20
No problem :)
When do you plan on doing another push of the code to NuGet?  I know there are about 2 features I am waiting on that were bugs that you have corrected.

**Comment by jacobslusser** [comment] 2015-12-22 04:33
Honestly, I hope to have a new build this weekend. It's the first time off I've had from work in a LONG time. :)

**Closed** 2015-12-26 18:05 UTC
Labels: bug
