### ISSUE TITLE
Problem with index out of bounds exception

### ISSUE THREAD

**Issue by bri1234** [jacobslusser/ScintillaNET#304] opened 2017-02-03 14:15 UTC
Hi,
sometimes I get an index out of bounds exception using ScintillaNET when assigning a new string to scintilla.Text property. In debug mode I see that the debug assertion in file LineCollection.cs function CharLineLength() line 65 fails:

Debug.Assert(index < Count);

The function CharLineLength() is called from DeletePerLine() when the debug assertion fails:

        private void DeletePerLine(int index)
        {
            Debug.Assert(index != 0);

            MoveStep(index);

            // Subtract the line length
            stepLength -= CharLineLength(index);

            // Remove the line
            perLineData.RemoveAt(index);

            // Move the step to the line before the one removed
            stepLine--;
        }

After taking a look at the source code I think the following line is wrong:

            stepLength -= CharLineLength(index);

I guess in function DeletePerLine() the line index starts at 1. But CharLineLength() seems to use a line index that starts at 0. Therefore I think the code should be changed to:

            stepLength -= CharLineLength(index - 1);

I am not sure if it is the right solution for the index out of bounds exception because in 99.9% the exception does not occur if I assign a new string to the Text property.

**Comment by jacobslusser** [comment] 2017-02-03 16:39
Interesting.

To be honest I'm skeptical of what you're saying because this code has been in use for a long time now and it pretty well tested.

Is it possible your text is malformed and contains some invalid characters? Or are you using multiple documents as explained in [Documents](https://github.com/jacobslusser/ScintillaNET/wiki/Documents) wiki article?

Would need to be able to reproduce this reliably to troubleshoot it.

**Comment by bri1234** [comment] 2017-02-03 19:22
I'm also skeptical because it works almost always :-)
But sometimes I get this index out of bounds exception. Unfortunately I did not made a screenshot from my debugging session.

The exception is thrown in the function CharLineLength().

        internal int CharLineLength(int index)
        {
            Debug.Assert(index >= 0);
            Debug.Assert(index < Count);

In debug mode the second assertion fails. "index" is equal to "count". The debug assertions shows me that the index used in this function can start at 0 and must be less than count. This function was called from function:

        private void DeletePerLine(int index)
        {
            Debug.Assert(index != 0);

            MoveStep(index);

            // Subtract the line length
            stepLength -= CharLineLength(index);

The first debug assertion shows me that the index in this function starts at 1. This function was called from:
        private void TrackDeleteText(NativeMethods.SCNotification scn)
        {
            var startLine = scintilla.DirectMessage(NativeMethods.SCI_LINEFROMPOSITION, new IntPtr(scn.position)).ToInt32();
             ....
here:
                var linesRemoved = scn.linesAdded * -1;
                for (int i = 0; i < linesRemoved; i++)
                {
                    // Deleted line
                    DeletePerLine(startLine + 1);
                }
In my debugging session startLine was 0. DeletePerLine() was called with startLine + 1 correctly.  But CharLineLength() fails if the last line is removed (when Count is 1).

I think the index out of range exception is thrown because the line index in function DeletePerLine() starts at 1 but starts at 0 in function CharLineLength().

Unfortunately this is hard to reproduce.

**Comment by jacobslusser** [comment] 2017-02-11 21:21
So, I put some time into this today and can't reproduce what you're describing. Here are some things to be aware of:

1. I would never write code that expects an index to start at index 1 rather than 0. :)
2. The `DeletePerLine` method would never use an index of 0 because the intention of this method is to delete line data and there is always at least one line in a Scintilla document. Hence, the call in `TrackDeleteText` to `DeletePerLine` is `DeletePerLine(startLine + 1);`. `DeletePerLine` should never be called with an index of `0`, hence the assertion `Debug.Assert(index != 0);` at the top of its definition.
3. When `DeletePerLine` wants to get the character length of a line it calls `CharLineLength` and it most definitely wants to use the same index and not one less. It wants the character length of the line it is working on -- and that index should always be less than `Count`.

I repeat my questions, are you using any malformed text -- text which has invalid byte codes that could throw off the calculation? Or are you using documents? Or are you ever accessing Scintilla from another thread besides the UI thread -- even indirectly?

Until we can prove otherwise I'm under the impression you have some bad input data or a race condition. Bad data could be the result of bad text or document handling. A race condition can occur if you are using multithreading incorrectly. Those are the only possibly scenarios I can think of where Scintilla(NET) would be trying to delete a line that doesn't exist.

**Comment by bri1234** [comment] 2017-03-16 11:56
Sorry for the late reply.

No I don't use malformed text. Only plain ASCII text. All accesses to Scintilla are from the main thread.

Please look again at my example. Please assume I have 1 line in Scintilla: property Count = 1

Now I delete text in Scintilla and TrackDeleteText() is called from Scintila:

private void TrackDeleteText(NativeMethods.SCNotification scn)
{
  var startLine = scintilla.DirectMessage(NativeMethods.SCI_LINEFROMPOSITION, new IntPtr(scn.position)).ToInt32();

In my debugging session startLine is 0 when I get the out of bounds exception.
The variable linesRemoved has the value 1 (scn.linesAdded is -1):

var linesRemoved = scn.linesAdded * -1;
for (int i = 0; i < linesRemoved; i++)
{
// Deleted line
DeletePerLine(startLine + 1);
}

Therefore the function DeletePerLine() is called once with parameter startLine + 1 = 1:

DeletePerLine(1);

This seems to be ok because of this piece of code that checks if the index is not equal to 0:

    private void DeletePerLine(int index)
    {
        Debug.Assert(index != 0);

Index starts at 1 here ;-)

But the next lines of code seems to be problematic:

        MoveStep(index);

        // Subtract the line length
        stepLength -= CharLineLength(index);

CharLineLength() is called with variable index. The variable index has the value 1:

CharLineLength(1);

And now please look at the function CharLineLength():

internal int CharLineLength(int index)
    {
        Debug.Assert(index >= 0);
        Debug.Assert(index < Count);

Count is 1 because there is only one line in Scintilla. But index is also 1 and therefore the debug assertion fails. I think this function fails always if all lines will be deleted and TrackDeleteText() is called.

Thank you very much for the time you spend to develop Scintilla.Net.

**Comment by jacobslusser** [comment] 2017-05-07 19:24
I'm closing this issue because it seems to be an isolated instance. We can re-open if necessary.

**Closed by jacobslusser** 2017-05-07 19:24 UTC
